apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path:  /home/pi/code-server-data # Replace with your desired local path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - x99  # Replace with the actual hostname of your microk8s node   
