---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
spec: {}
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/jellyfin/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-config-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy: {}
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - image: jellyfin/jellyfin
        name: jellyfin
        resources: {}
        volumeMounts:
        - name: jellyfin-config
          mountPath: /config 
        - name: my8000
          mountPath: /8000
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyin-config-pvc 
        - name: my8000
          hostPath:
            path: /mnt/8000SAM1/8000
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app: jellyfin
  type: LoadBalancer
status:
  loadBalancer: {}
